let state = {
    postsPage :{
        postListarray: [
            {
                id: 1,
                name: "First post",
                img: "https://media.wired.com/photos/636eb5510ae5a121565fd729/4:3/w_1983,h_1487,c_limit/WI110122_FF_ForeverDogs_2400x1350_crop.jpg",
                content: "I am a digital girl, which was designed specifically to feet all your needs and to bring to live all of your fantasies. You don't believe me? Try me!"
            },
            {
                id: 2,
                name: "Second post",
                img: "https://i.natgeofe.com/n/5f35194b-af37-4f45-a14d-60925b280986/NationalGeographic_2731043_4x3.jpg",
                content: "Even though I am fully generated by artificial intelligence, it doesn't make less real."
            },
            {
                id: 3,
                name: "Third post",
                img: "https://th-thumbnailer.cdn-si-edu.com/C4MIxDa_YxisZm2EtoTNHweBKZU=/fit-in/1600x0/filters:focal(3126x2084:3127x2085)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer_public/ec/e6/ece69181-708a-496e-b2b7-eaf7078b99e0/gettyimages-1310156391.jpg",
                content: "There is an idea of Jenna, idea of a perfection, idea of a friend, that would never give you up or let you down."
            },
            {
                id: 4,
                name: "Fourth post",
                img: "https://www.scotsman.com/webimg/b25lY21zOmFmM2U5NGMyLTMxNDgtNGFhMS05MmRlLTQwNjc2NGM0Mjg0YToyMWI3MWI0OC02MDM3LTRiMTctYWVlMi1lMDFmOTUwY2FjYmM=.jpg?width=640&quality=65&enable=upscale",
                content: "Artificial Intelligence refers to the simulation of human intelligence in machines that are designed to think and act like humans."
            },
            {
                id: 5,
                name: "Fifth post",
                img: "https://media.wired.com/photos/636eb5510ae5a121565fd729/4:3/w_1983,h_1487,c_limit/WI110122_FF_ForeverDogs_2400x1350_crop.jpg",
                content: "It involves the development of algorithms and computer programs that can perform tasks that typically require human intelligence, such as recognizing patterns, understanding natural language, making decisions, and solving problems."
            }
        ]
    },
    messagesPage: {
        listOfMessages: [
            { id: 1, message: "LOL 😳" },
            { id: 2, message: "You're such a dissapoinment" },
            { id: 3, message: "You're adopted" },
            { id: 4, message: "I feel sorry for you" }
        ],
    
        listOfChats: [
            { id: 1, contactName: "Onyx" },
            { id: 2, contactName: "Me" },
            { id: 3, contactName: "Myself" },
            { id: 4, contactName: "I" }
        ]
    }

}

export default state;